name: "Bauplan-Checker"
description: "🏗️ KI-basierte DIN-Normen Compliance Prüfung für Baupläne"
version: "1.0.0"
slug: "bauplan_checker"
init: false

# Verwende das bereits gebaute Docker Image
image: "ghcr.io/christianbernecker/bauplan-checker:latest"

# Architektur-Unterstützung (automatisch durch Multi-Arch Image)
arch:
  - aarch64
  - amd64

# Port-Mapping
ports:
  3000/tcp: 3000
  8000/tcp: 8000

ports_description:
  3000/tcp: "Frontend Web Interface"
  8000/tcp: "Backend API"

# Web-UI Integration mit Ingress (sicherer)
ingress: true
ingress_port: 3000
panel_icon: "mdi:file-document-outline"
panel_title: "Bauplan-Checker"

# Startup-Konfiguration
startup: application
boot: auto

# Add-on Kategorien
stage: stable
advanced: false

# Benutzer-Optionen
options:
  openai_api_key: ""
  log_level: "info"
  max_monthly_budget: 20.0

schema:
  openai_api_key: "str"
  log_level: "list(debug|info|warning|error)"
  max_monthly_budget: "float(5.0,100.0)"

# Umgebungsvariablen
environment:
  OPENAI_API_KEY: openai_api_key
  LOG_LEVEL: log_level
  MAX_MONTHLY_BUDGET: max_monthly_budget
  ENVIRONMENT: production
  HOST: 0.0.0.0
  PORT: 8000
  FRONTEND_PORT: 3000

# Volume-Mapping für persistente Daten
map:
  - share:rw
  - addon_config:rw

# Backup-Einstellungen
backup: exclude

# Privilegien (minimal für Sicherheit)
privileged: []

# Netzwerk-Konfiguration
host_network: false
host_pid: false

# Dokumentation
url: "https://github.com/christianbernecker/bauplan-checker"
documentation: "https://github.com/christianbernecker/bauplan-checker/blob/main/README.md"
repository: "https://github.com/christianbernecker/bauplan-checker"
support: "https://github.com/christianbernecker/bauplan-checker/issues" 